language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "s5wECW7lYEXmG4zuG7zorfdmGjxkhm9m6tLyECqiZa6oQbE+nIHTkoyCQhtOe/qklhV4HwTSEu53vmJcK21hpDm39tK4OydCWBDYU+VOdeFG9fHnxWtVJEzthplRVaWDJTRclFc84pJBX19tJB5FvPlJHiPWvsUMkp3KLWbne6Tobf7ejtvam0Z6SYbFaZfgVpQaZlBlwQFYPI2/eYtnuIXznYgcd6L1ee496DBk9kUBHTbND3PdZWOIhKoDI0w2kTAIW2ZtGMltwPZORS6kxx3eRt2TiqqazCqbQlKx42aB0vXh4N0nmQZfnDAu61yksTH5zilQZIr2XBDdsyIPafwJrlnAq6n0RwUdWfvMRfYe5CDbDD35wSVun3eGhTF2qM+tEYv0Hn3qho0JS0MNKqkIqdOOqapk1jkOD23O0HnOQ1HhW7IlcTNl5MLvToi11In+xa0fPdpViS4/W2LInUmcz1j7cFs1SeYoIvx5n+W6uI1rKwOQdOjYjg8GcvBlYtRc0F9QRIjZ4EwCpAafsj/vPG0RT+FINhk5fyG5Tn/OGFLjGXZfLYTgKHrqCZrIlmJ+EUoo+V6gNUJJOm2K358fBxPVlvqy2zdosc8KoGK50jQ0RsTtgzXJSayrqeUpDnipIebsIGinWAeLqEe4xOnurP/qZCyi6GSwoXqCboI="